apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace = ${kubernetes_namespace.main.id}
  name: ${local.secret_provider_class_name}
spec:
  provider: azure
  secretObjects: # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ${local.ingress_secret_name}
    type: kubernetes.io/tls
    data: 
    - objectName: ${var.ingress_cert_name}
      key: tls.key
    - objectName: ${var.ingress_cert_name}
      key: tls.crt
  parameters:
    tenantId: ${azurerm_user_assigned_identity.main.tenant_id}
    userAssignedIdentityID: ${azurerm_user_assigned_identity.main.client_id}
    keyvaultName: ${data.azurerm_key_vault.main.name}
    objects: |
      array:
        - |
          objectName: ${var.ingress_cert_name}
          objectType: secret 