apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: keyvault-client
spec:
  provider: azure
  parameters:
    tenantID: "YOUR_TENANT_ID"
    clientID: "YOUR_CLIENT_ID"
    keyvaultName: kv-arcbio-akswi
    objects: |
      array:
        - |
          objectName: randomSecret
          objectType: secret
