apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: keyvault-client
spec:
  provider: azure
  parameters:
    clientID: a5091b9a-dcfa-4481-8505-6b6b20437aa6
    keyvaultName: kv-arcbio-akswi
    objects: |
      array:
        - |
          objectName: randomSecret
          objectType: secret
    tenantID: 16b3c013-d300-468d-ac64-7eda0820b6d3